Repository stacks-network/gaia, pull requests merged in 2019-01, with the labels that each got.

#172 Hotfix/y2k19 auth fix
  hub/package.json
  hub/src/server/authentication.js
  hub/test/src/testServer.js
Labels: bug, production

#175 Hotfix for promise rejection behavior
  hub/CHANGELOG.md
  hub/package.json
  hub/src/server/authentication.js
  hub/src/server/server.js
  hub/test/src/testHttp.js
Labels: bug

#173 Deprecate timestamps
  hub/package-lock.json
  hub/package.json
  hub/src/server/authentication.js
  hub/test/src/testAuth.js
  hub/test/src/testServer.js
Labels: chore
